"""Initial clean setup

Revision ID: 28ad91e26a2f
Revises: 8c2bbd5f3c70
Create Date: 2025-05-30 12:54:00.672005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ad91e26a2f'
down_revision: Union[str, None] = '8c2bbd5f3c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'price')
    # ### end Alembic commands ###
